// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/dashboard/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListSeedKubeLBTenantsReader is a Reader for the ListSeedKubeLBTenants structure.
type ListSeedKubeLBTenantsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSeedKubeLBTenantsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSeedKubeLBTenantsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListSeedKubeLBTenantsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListSeedKubeLBTenantsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewListSeedKubeLBTenantsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListSeedKubeLBTenantsOK creates a ListSeedKubeLBTenantsOK with default headers values
func NewListSeedKubeLBTenantsOK() *ListSeedKubeLBTenantsOK {
	return &ListSeedKubeLBTenantsOK{}
}

/*
ListSeedKubeLBTenantsOK describes a response with status code 200, with default header values.

KubeLBTenant
*/
type ListSeedKubeLBTenantsOK struct {
	Payload []*models.KubeLBTenant
}

// IsSuccess returns true when this list seed kube l b tenants o k response has a 2xx status code
func (o *ListSeedKubeLBTenantsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list seed kube l b tenants o k response has a 3xx status code
func (o *ListSeedKubeLBTenantsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list seed kube l b tenants o k response has a 4xx status code
func (o *ListSeedKubeLBTenantsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list seed kube l b tenants o k response has a 5xx status code
func (o *ListSeedKubeLBTenantsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list seed kube l b tenants o k response a status code equal to that given
func (o *ListSeedKubeLBTenantsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListSeedKubeLBTenantsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/kubelb/tenants][%d] listSeedKubeLBTenantsOK  %+v", 200, o.Payload)
}

func (o *ListSeedKubeLBTenantsOK) String() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/kubelb/tenants][%d] listSeedKubeLBTenantsOK  %+v", 200, o.Payload)
}

func (o *ListSeedKubeLBTenantsOK) GetPayload() []*models.KubeLBTenant {
	return o.Payload
}

func (o *ListSeedKubeLBTenantsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSeedKubeLBTenantsUnauthorized creates a ListSeedKubeLBTenantsUnauthorized with default headers values
func NewListSeedKubeLBTenantsUnauthorized() *ListSeedKubeLBTenantsUnauthorized {
	return &ListSeedKubeLBTenantsUnauthorized{}
}

/*
ListSeedKubeLBTenantsUnauthorized describes a response with status code 401, with default header values.

EmptyResponse is a empty response
*/
type ListSeedKubeLBTenantsUnauthorized struct {
}

// IsSuccess returns true when this list seed kube l b tenants unauthorized response has a 2xx status code
func (o *ListSeedKubeLBTenantsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list seed kube l b tenants unauthorized response has a 3xx status code
func (o *ListSeedKubeLBTenantsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list seed kube l b tenants unauthorized response has a 4xx status code
func (o *ListSeedKubeLBTenantsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list seed kube l b tenants unauthorized response has a 5xx status code
func (o *ListSeedKubeLBTenantsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list seed kube l b tenants unauthorized response a status code equal to that given
func (o *ListSeedKubeLBTenantsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *ListSeedKubeLBTenantsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/kubelb/tenants][%d] listSeedKubeLBTenantsUnauthorized ", 401)
}

func (o *ListSeedKubeLBTenantsUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/kubelb/tenants][%d] listSeedKubeLBTenantsUnauthorized ", 401)
}

func (o *ListSeedKubeLBTenantsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListSeedKubeLBTenantsForbidden creates a ListSeedKubeLBTenantsForbidden with default headers values
func NewListSeedKubeLBTenantsForbidden() *ListSeedKubeLBTenantsForbidden {
	return &ListSeedKubeLBTenantsForbidden{}
}

/*
ListSeedKubeLBTenantsForbidden describes a response with status code 403, with default header values.

EmptyResponse is a empty response
*/
type ListSeedKubeLBTenantsForbidden struct {
}

// IsSuccess returns true when this list seed kube l b tenants forbidden response has a 2xx status code
func (o *ListSeedKubeLBTenantsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list seed kube l b tenants forbidden response has a 3xx status code
func (o *ListSeedKubeLBTenantsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list seed kube l b tenants forbidden response has a 4xx status code
func (o *ListSeedKubeLBTenantsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this list seed kube l b tenants forbidden response has a 5xx status code
func (o *ListSeedKubeLBTenantsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this list seed kube l b tenants forbidden response a status code equal to that given
func (o *ListSeedKubeLBTenantsForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *ListSeedKubeLBTenantsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/kubelb/tenants][%d] listSeedKubeLBTenantsForbidden ", 403)
}

func (o *ListSeedKubeLBTenantsForbidden) String() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/kubelb/tenants][%d] listSeedKubeLBTenantsForbidden ", 403)
}

func (o *ListSeedKubeLBTenantsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListSeedKubeLBTenantsDefault creates a ListSeedKubeLBTenantsDefault with default headers values
func NewListSeedKubeLBTenantsDefault(code int) *ListSeedKubeLBTenantsDefault {
	return &ListSeedKubeLBTenantsDefault{
		_statusCode: code,
	}
}

/*
ListSeedKubeLBTenantsDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListSeedKubeLBTenantsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list seed kube l b tenants default response
func (o *ListSeedKubeLBTenantsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list seed kube l b tenants default response has a 2xx status code
func (o *ListSeedKubeLBTenantsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list seed kube l b tenants default response has a 3xx status code
func (o *ListSeedKubeLBTenantsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list seed kube l b tenants default response has a 4xx status code
func (o *ListSeedKubeLBTenantsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list seed kube l b tenants default response has a 5xx status code
func (o *ListSeedKubeLBTenantsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list seed kube l b tenants default response a status code equal to that given
func (o *ListSeedKubeLBTenantsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListSeedKubeLBTenantsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/kubelb/tenants][%d] listSeedKubeLBTenants default  %+v", o._statusCode, o.Payload)
}

func (o *ListSeedKubeLBTenantsDefault) String() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/kubelb/tenants][%d] listSeedKubeLBTenants default  %+v", o._statusCode, o.Payload)
}

func (o *ListSeedKubeLBTenantsDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListSeedKubeLBTenantsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
